Repository dynotx/liminal-orm, pull requests merged in 2024-12, with the labels that each got.

#62 add translation link
  liminal/enums/benchling_api_field_type.py
  liminal/enums/benchling_field_type.py
  liminal/mappers.py
Labels: type:minor-enhancement, semver:patch

#54 Fix 49 warehouse names
  docs/reference/entity-schemas.md
  liminal/base/properties/base_field_properties.py
  liminal/connection/benchling_connection.py
  liminal/connection/benchling_service.py
  liminal/entity_schemas/compare.py
  liminal/orm/base_model.py
  liminal/utils.py
Labels: type:task, semver:patch

#64 make query function optional
  liminal/entity_schemas/generate_files.py
  liminal/orm/base_model.py
Labels: type:minor-enhancement, semver:patch

#66 change array to json for column sqlalchemy type
  liminal/orm/column.py
Labels: type:bug, semver:patch

#69 revert incorrect logic from previous pr
  liminal/base/properties/base_field_properties.py
  liminal/entity_schemas/compare.py
  liminal/orm/base_model.py
Labels: type:bug, semver:patch

#67 be able to define archived fields on entity schemas
  liminal/base/properties/base_field_properties.py
  liminal/base/properties/base_schema_properties.py
  liminal/entity_schemas/compare.py
  liminal/entity_schemas/utils.py
  liminal/orm/base_model.py
  liminal/orm/column.py
  liminal/orm/schema_properties.py
  liminal/tests/conftest.py
  liminal/tests/test_entity_schema_compare.py
Labels: type:minor-enhancement, semver:minor

#72 block warehouse name changes to operations
  liminal/base/base_operation.py
  liminal/cli/live_test_dropdown_migration.py
  liminal/cli/live_test_entity_schema_migration.py
  liminal/dropdowns/operations.py
  liminal/entity_schemas/operations.py
  liminal/migrate/components.py
Labels: type:task, semver:patch

#70 added molecule entity type and updated references
  liminal/entity_schemas/generate_files.py
  liminal/enums/benchling_entity_type.py
  liminal/enums/benchling_folder_item_type.py
  liminal/mappers.py
  liminal/orm/mixins.py
Labels: type:bug, note:feature request

#73 Add releases section to docs
  .markdownlint.json
  CONTRIBUTING.md
  docs/contributing.md
  docs/future-direction.md
  docs/release-notes.md
  docs/theme/announce.html
  docs/theme/main.html
  mkdocs.yml
Labels: type:documentation

#76 alias warehouse names for columns
  docs/reference/entity-schemas.md
  liminal/orm/column.py
  liminal/tests/conftest.py
  liminal/tests/test_entity_schema_compare.py
Labels: semver:patch

#77 fix bug with UpdateEntitySchemaField ordering
  liminal/entity_schemas/generate_files.py
  liminal/entity_schemas/operations.py
Labels: type:bug, semver:patch

#80 Add registry_entity and schema as base tables
  liminal/orm/base_model.py
  liminal/orm/base_tables/registry_entity.py
  liminal/orm/base_tables/schema.py
  liminal/orm/base_tables/user.py
Labels: type:task, semver:patch

#79 add fieldsets parameters to benchling connection for validation
  liminal/connection/benchling_connection.py
  liminal/entity_schemas/operations.py
Labels: semver:patch, note:feature request

#83 change error to warning if there are multiple schemas with the same prefix
  liminal/orm/base_model.py
Labels: type:bug, semver:patch
