Repository dynotx/liminal-orm, pull requests merged in 2025-01, with the labels that each got.

#89 update order indexes
  liminal/dropdowns/operations.py
  liminal/entity_schemas/operations.py
Labels: type:task, semver:patch

#84 cover chip naming
  liminal/base/properties/base_schema_properties.py
  liminal/entity_schemas/entity_schema_models.py
  liminal/entity_schemas/tag_schema_models.py
  liminal/entity_schemas/utils.py
  liminal/orm/schema_properties.py
  liminal/tests/conftest.py
  liminal/tests/test_entity_schema_compare.py
Labels: type:minor-enhancement, semver:major

#96 ignore non .py files in versions dir
  liminal/migrate/revisions_timeline.py
Labels: type:bug, semver:patch
