Repository dynotx/liminal-orm, pull requests merged in 2025-02, with the labels that each got.

#98 move prefix warning to validate_model
  liminal/orm/base_model.py
Labels: type:bug, type:task, semver:patch

#88 Add coverage for namesets
  liminal/base/base_operation.py
  liminal/base/name_template_parts.py
  liminal/base/properties/base_name_template.py
  liminal/dropdowns/operations.py
  liminal/entity_schemas/api.py
  liminal/entity_schemas/compare.py
  liminal/entity_schemas/generate_files.py
  liminal/entity_schemas/operations.py
  liminal/entity_schemas/tag_schema_models.py
  liminal/entity_schemas/utils.py
  liminal/enums/benchling_entity_type.py
  liminal/enums/name_template_part_type.py
  liminal/external/__init__.py
  liminal/orm/base_model.py
  liminal/orm/name_template.py
  liminal/orm/schema_properties.py
  liminal/tests/conftest.py
  liminal/tests/test_entity_schema_compare.py
Labels: type:minor-enhancement, semver:major

#100 Handle no schemas imported gracefully
  liminal/dropdowns/compare.py
  liminal/entity_schemas/compare.py
Labels: type:bug, semver:patch

#101 update documentation with v2.0.0 release
  README.md
  docs/blog/dynotx-recommended-sop.md
  docs/contributing.md
  docs/future-direction.md
  docs/getting-started/downgrading.md
  docs/getting-started/first-migration.md
  docs/getting-started/installation.md
  docs/getting-started/prerequisites.md
  docs/getting-started/setup.md
  docs/index.md
  docs/reference/benchling-connection.md
  docs/reference/benchling-session.md
  docs/reference/dropdowns.md
  docs/reference/entity-schemas.md
  docs/reference/operations.md
  docs/reference/revision-file.md
  docs/reference/validation.md
  docs/release-notes.md
  docs/theme/announce.html
  liminal/base/properties/base_schema_properties.py
  liminal/orm/schema_properties.py
  liminal/utils.py
  mkdocs.yml
Labels: type:documentation

#102 Move name template parts to orm
  docs/reference/entity-schemas.md
  liminal/base/name_template_parts.py
  liminal/base/properties/base_name_template.py
  liminal/entity_schemas/generate_files.py
  liminal/entity_schemas/tag_schema_models.py
  liminal/external/__init__.py
  liminal/orm/base_model.py
  liminal/orm/name_template.py
  liminal/orm/name_template_parts.py
  liminal/tests/test_entity_schema_compare.py
Labels: type:task, semver:patch

#103 update docs to show order matters for dropdown values and schema fields
  docs/reference/dropdowns.md
  docs/reference/entity-schemas.md
Labels: type:documentation

#104 allow liminal_validator functions to return an optional custom report
  README.md
  docs/reference/validation.md
  liminal/validation/__init__.py
Labels: type:bug, semver:patch

#106 translation link bugfix
  liminal/entity_schemas/generate_files.py
  liminal/entity_schemas/tag_schema_models.py
  liminal/enums/benchling_field_type.py
  liminal/mappers.py
  liminal/orm/column.py
Labels: type:bug, semver:patch

#105 Add keep names to naming strategy
  liminal/enums/benchling_naming_strategy.py
Labels: type:bug, semver:patch

#107 fix creating new entity schema with template based naming strategy
  liminal/base/base_operation.py
  liminal/entity_schemas/compare.py
  liminal/entity_schemas/operations.py
Labels: type:bug, semver:patch

#109 implement sequence constraint logic constraints
  docs/reference/entity-schemas.md
  liminal/base/properties/base_schema_properties.py
  liminal/entity_schemas/entity_schema_models.py
  liminal/entity_schemas/operations.py
  liminal/entity_schemas/tag_schema_models.py
  liminal/entity_schemas/utils.py
  liminal/enums/__init__.py
  liminal/enums/benchling_entity_type.py
  liminal/enums/sequence_constraint.py
  liminal/orm/base_model.py
  liminal/orm/schema_properties.py
Labels: type:bug, semver:patch

#111 add units to benchling tag schema field schema
  liminal/entity_schemas/tag_schema_models.py
Labels: type:bug, semver:patch

#112 part link in mappers
  liminal/enums/benchling_field_type.py
  liminal/mappers.py
  liminal/orm/column.py
Labels: type:bug, semver:patch

#116 generate files decimal places bug fix
  liminal/entity_schemas/generate_files.py
Labels: type:bug, semver:patch

#118 add COMPLEX_POLYMER_COMPONENT and LINKED_BIOENTITY_REGISTRY_IDENTIFIER to name template parts
  liminal/entity_schemas/tag_schema_models.py
  liminal/enums/name_template_part_type.py
  liminal/external/__init__.py
  liminal/orm/name_template_parts.py
Labels: type:bug, semver:patch

#120 update snake case and pascale case functions
  liminal/dropdowns/generate_files.py
  liminal/entity_schemas/generate_files.py
  liminal/entity_schemas/operations.py
  liminal/utils.py
  liminal/validation/__init__.py
Labels: type:bug, semver:patch
