Repository dynotx/liminal-orm, pull requests merged in 2025-03, with the labels that each got.

#122 add TenantConfigFlags to liminal.connection init
  liminal/connection/__init__.py
Labels: type:bug, semver:patch

#121 Change autogenerate to revisions
  docs/blog/dynotx-recommended-sop.md
  docs/reference/entity-schemas.md
  docs/reference/operations.md
  docs/reference/revision-file.md
  liminal/cli/cli.py
  liminal/cli/controller.py
  liminal/migrate/revisions_timeline.py
Labels: type:task, semver:minor

#123 fix multi relationship
  liminal/base/name_template_parts.py
  liminal/entity_schemas/generate_files.py
  liminal/orm/base_model.py
  liminal/orm/relationship.py
Labels: type:bug, semver:major
