Repository dynotx/liminal-orm, pull requests merged in 2025-05, with the labels that each got.

#138 specify type of files to generate in generate-files command
  liminal/cli/cli.py
  liminal/cli/controller.py
  liminal/entity_schemas/generate_files.py
  liminal/results_schemas/generate_files.py
Labels: type:minor-enhancement, semver:minor

#140 update docs for v4 and push deprecation to v5 release
  docs/future-direction.md
  docs/getting-started/prerequisites.md
  docs/getting-started/setup.md
  docs/getting-started/synchronizing-results-schemas.md
  docs/reference/entity-schemas.md
  docs/reference/results-schemas.md
  docs/reference/validation.md
  docs/release-notes.md
  docs/theme/announce.html
  liminal/base/name_template_parts.py
  liminal/cli/cli.py
  liminal/cli/utils.py
  liminal/orm/base_results_model.py
  liminal/orm/relationship.py
  mkdocs.yml
Labels: type:documentation

#141 set httpx logger level to warning in BenchlingService
  liminal/connection/benchling_service.py
Labels: type:task, semver:patch

#145 remote liminal revision_id bug fixes
  liminal/cli/cli.py
  liminal/connection/benchling_service.py
  liminal/entity_schemas/utils.py
Labels: type:bug, semver:patch

#144 Adding missing types for json and bool
  .gitignore
  liminal/enums/benchling_api_field_type.py
  liminal/enums/benchling_field_type.py
  liminal/mappers.py
Labels: type:minor-enhancement, semver:minor

#146 security upgrade - tornado to 6.5.0
  poetry.lock
  pyproject.toml
Labels: type:dependency, semver:patch

#148 overwrite flag in generate-files applies to files
  liminal/cli/cli.py
  liminal/dropdowns/generate_files.py
  liminal/entity_schemas/generate_files.py
  liminal/results_schemas/generate_files.py
Labels: type:bug, semver:patch

#150 Migrate poetry to uv
  .github/workflows/cicd.yml
  .github/workflows/pre-release.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  docs/contributing.md
  poetry.lock
  pyproject.toml
  uv.lock
Labels: type:dependency, semver:patch

#151 update env.py setup docs
  docs/getting-started/setup.md
Labels: type:documentation
